# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# see https://github.com/folke/lazy.nvim/blob/main/.github/workflows/ci.yml
name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:

      - name: Environment information
        run: |
          uname
          uname -a

      - uses: actions/checkout@v2

      - name: Download Neovim
        run: |
          wget -q https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.deb -O /tmp/nvim.deb
          sudo dpkg -i /tmp/nvim.deb

      - name: Setup upterm session
        env:
          DEBUG_SSH: ${{ secrets.DebugSSH }}
        if: ${{ env.DEBUG_SSH == 'true' }}
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          # limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: hjdivad,rwjblue

      - name: test
        run: |
          nvim --version
          [ ! -d tests ] && exit 0
          CI=true nvim --headless -u tests/init.lua -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/init.lua', sequential = true }"
